apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rhiaqey-producer.fullname" . }}
  labels:
    {{- include "rhiaqey-producer.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rhiaqey-producer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rhiaqey-producer.selectorLabels" . | nindent 8 }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              {{- include "rhiaqey-producer.selectorLabels" . | nindent 6 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rhiaqey-producer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-private
              containerPort: {{ .Values.producer.private_port }}
              protocol: TCP
            - name: http-public
              containerPort: {{ .Values.producer.public_port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /alive
              port: http-private
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /alive
              port: http-private
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 15
          env:
            - name: ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAME
              value: {{ .Release.Name | quote }}
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PUBLIC_PORT
              value: {{ .Values.producer.public_port | quote }}
            - name: PRIVATE_PORT
              value: {{ .Values.producer.private_port | quote }}
            - name: PRIVATE_PORT
              value: {{ .Values.producer.private_port | quote }}
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.producer.keys.name }}
                  key: {{ .Values.producer.keys.private }}
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.producer.keys.name }}
                  key: {{ .Values.producer.keys.public }}
            - name: RUST_LOG
              value: {{ .Values.producer.log_level | quote }}
            {{ if .Values.producer.redis.sentinel_mode }}
            - name: REDIS_SENTINEL_ADDRESSES
              value: {{ .Values.producer.redis.sentinel_addresses | quote }}
            {{ else }}
            - name: REDIS_ADDRESS
              value: {{ .Values.producer.redis.address | quote }}
            {{ end }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "redis"
                  key: "redis-password"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
