name: Commit

on:
  push:
  pull_request:
    branches:
      - master

env:
  CI: true
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Build
        run: cargo build --features all

      - name: Run tests
        run: cargo test --features all

  CI:
    runs-on: ubuntu-latest
    needs:
      - Setup
    strategy:
      matrix:
        producers: [
          {binary: "ecb-daily", features: "ecb"},
          {binary: "iss-astros", features: "iss"},
          {binary: "iss-position", features: "iss"},
          {binary: "pinger", features: "pinger"},
          {binary: "rss", features: "rss"},
          {binary: "ticker", features: "ticker"},
          {binary: "yahoo", features: "yahoo"}
        ]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
        with:
          context: .
          push: false
          build-args: |
            BINARY=${{ matrix.producers.binary }}
            FEATURES=${{ matrix.producers.features }}
