name: Commit

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master

env:
  CI: true
  CARGO_TERM_COLOR: always

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Build
        run: cargo build --all-features

      - name: Run tests
        run: cargo test --all-features

  CI:
    runs-on: ubuntu-latest
    needs:
      - Setup
    strategy:
      matrix:
        producers: [
          { image: "rhiaqey/ecb-daily", binary: "ecb-daily", features: "ecb" },
          { image: "rhiaqey/iss-astros", binary: "iss-astros", features: "iss" },
          { image: "rhiaqey/iss-position", binary: "iss-position", features: "iss" },
          { image: "rhiaqey/pinger", binary: "pinger", features: "pinger" },
          { image: "rhiaqey/rss", binary: "rss", features: "rss" },
          { image: "rhiaqey/ticker", binary: "ticker", features: "ticker" },
          { image: "rhiaqey/yahoo", binary: "yahoo", features: "yahoo" }
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image for ${{ matrix.producers.binary }}
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56
        with:
          context: .
          push: false
          tags: ${{ matrix.producers.image }}:latest
          build-args: |
            BINARY=${{ matrix.producers.binary }}
            FEATURES=${{ matrix.producers.features }}
