name: Commit

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

env:
  CI: true
  CARGO_TERM_COLOR: always
  OPENSSL_STATIC: 1
  OPENSSL_NO_VENDOR: 0

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: cargo build --all-features

      - name: Run tests
        run: cargo test --all-features

  CI:
    runs-on: ubuntu-latest
    needs:
      - Setup
    strategy:
      matrix:
        producers: [
          { image: "rhiaqey/ecb-daily", binary: "ecb-daily" },
          { image: "rhiaqey/iss-astros", binary: "iss-astros" },
          { image: "rhiaqey/iss-position", binary: "iss-position" },
          { image: "rhiaqey/pinger", binary: "pinger" },
          { image: "rhiaqey/rss", binary: "rss" },
          { image: "rhiaqey/ticker", binary: "ticker" },
          { image: "rhiaqey/yahoo", binary: "yahoo" }
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build docker image for ${{ matrix.producers.binary }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ matrix.producers.image }}:latest
          build-args: |
            BINARY=${{ matrix.producers.binary }}
