name: PR Merge

on:
  push:
    branches:
      - master
      - adopt-new-ci

env:
  CI: true
  IMAGE_NAME: rhiaqey/hub
  CARGO_TERM_COLOR: always
  CARGO_TAG_NAME: "GitHub Actions"
  CARGO_TAG_EMAIL: "github-actions@users.noreply.github.com"

permissions:
  contents: write

jobs:
  Setup:
    runs-on: ubuntu-latest

    outputs:
      git_tag: ${{ steps.prepare_tag.outputs.GIT_TAG }}
      git_branch: ${{ steps.extract_branch.outputs.GIT_BRANCH }}

    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-tag

      - id: prepare_tag
        run: |
          cargo tag patch
          GIT_TAG="$(cargo tag current)"
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_OUTPUT
          echo "Found $GIT_TAG tag"
          git tag -d $GIT_TAG

      - id: extract_branch
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: ${{ env.IMAGE_NAME }}

  ECBDaily:
    runs-on: ubuntu-latest
    needs:
      - Setup
    env:
      GIT_TAG: ${{ needs.Setup.outputs.git_tag }}
      GIT_BRANCH: ${{ needs.Setup.outputs.git_branch }}
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-tag
      - run: |
          echo "Do we have access to git tag $GIT_TAG and branch $GIT_BRANCH"
          echo "Or should we access via env ${{ env.GIT_TAG }} and ${{ env.GIT_BRANCH }}"
          echo "What about ${{ needs.Setup.outputs.git_tag }} and ${{ needs.Setup.outputs.git_branch }}"
          git status
          cat Cargo.toml
          cargo tag patch
          cat Cargo.toml
